### ISSUE TITLE
@wakaru/ide:build: RollupError: Identifier "a" has already been declared

### ISSUE THREAD

**Issue by milahu** [pionxzh/wakaru#109] opened 2024-02-13 08:06 UTC
### Describe the bug

build error with wakaru version af738e030a53374da4d8f88231bca48e2650a269

### Steps to reproduce

```
git clone --depth=1 https://github.com/pionxzh/wakaru
cd wakaru
pnpm install
npm run build
```

### Expected behavior

build

### Actual behavior

```
$ npm run build 

> @wakaru/ide@0.0.0 build
> vite build

vite v5.0.2 building for production...
[plugin:vite:resolve] Module "constants" has been externalized for browser compatibility, imported by "/wakaru/node_modules/.pnpm/flow-parser@0.212.0/node_modules/flow-parser/flow_parser.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 312 modules transformed.
[commonjs--resolver] Identifier "a" has already been declared
file: /wakaru/node_modules/.pnpm/jscodeshift@0.15.1_@babel+preset-env@7.23.3/node_modules/jscodeshift/index.js:432:0
430: a=hK(a),b=hK(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
431: 12520:var
432: a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
     ^
433: 246:case
434: 254:default:if(au8(e)){aQ("compare: continuation value");break}if(a.length!=b.length)return a.length<b.length?-1:1;if...
error during build:
RollupError: Identifier "a" has already been declared
    at error (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Module.error (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:12737:16)
    at BlockScope.addDeclaration (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:7520:32)
    at Identifier.declare (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:7188:39)
    at VariableDeclarator.declareDeclarator (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:10178:17)
    at VariableDeclaration.initialise (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:11843:24)
    at new NodeBase (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:4607:14)
    at new VariableDeclaration (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:11815:1)
    at SwitchCase.parseNode (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:4718:27)
    at new NodeBase (file:///wakaru/node_modules/.pnpm/rollup@4.5.2/node_modules/rollup/dist/es/shared/node-entry.js:4606:14)
```

**Comment by pionxzh** [comment] 2024-02-14 08:38
It looks like a bug from `vite` v5. Fixed by downgrading to v4. Let me test more and find the root cause.

**Closed** 2024-02-14 08:38 UTC
Labels: internal

**Comment by pionxzh** [comment] 2024-02-14 08:45
This is related to https://github.com/rollup/rollup/issues/5259.

I have bumped `vite` back to v5 with the latest `rollup`.
